version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: example_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5444:5432"
